apiVersion: apps/v1
kind: Deployment
metadata: 
  name: braunson-young
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: braunson-young
  template:
    metadata:
      labels:
        app: braunson-young
    spec: 
      containers:
        - name: braunson-young
          image: gcr.io/the-dope-team/teamwebsite:latest
          ports: 
          - containerPort: 3000
          resources:
            limits:
              cpu: 100m
              memory: 250M
            requests:
              cpu: 50m
              memory: 100M
---
apiVersion: v1
kind: Service
metadata: 
  name: braunson_pod-service
spec:
  selector: 
    app: brauson-young
  type: LoadBalancer
  ports: 
  - port: 80 
    targetPort: 80
---
