apiVersion: apps/v1
kind: Deployment
metadata: 
    name: gilber-chen
spec: 
  replicas: 1 
  selector: 
    matchLabels:
      app: gilber-chen
  template: 
      metadata: 
        labels: 
          app: gilber-chen 
      spec: 
        containers: 
        - name: gilber-chen 
          image: gcr.io/the-dope-team/teamwebsite:latest
          ports: 
          - containerPort: 3000
          resources: 
            limits: 
              cpu: 100m
              memory: 250M 
            requests: 
              cpu: 50m 
              memory: 100M
---
apiVersion: v1 
kind: Service 
metadata: 
  name: gilber-chen-service 
spec: 
  selector: 
    app: gilber-chen
    type: LoadBalance
  ports:
  - port: 80 
    targetPort: 3000
              